name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Check format
        run: npm run lint
